name: Fort Dalles Fourth
favicon: null
layout_spectrum: 0.31572
typography_spectrum: 0.68774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#115182'
    - '#eb222d'
    - '#6d92ad'
    - '#d3565d'
  brandStrength: 0.9760585555341095
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
